name: Guitar Starz
analytics:
  twitter: '#PowerStrat'
purpose:
  - type: external
    url: 'Http://YouTube.com/guitarstarz'
    label: 'Http://YouTube.com/guitarstarz'
github: true
description: 'Everything. Guitar. '
author: {}
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
content: []
layout_spectrum: 1
color:
  lightness: 0.6847476
  brandColors:
    - '#110205'
    - '#5B4D4C'
    - '#FF008F'
    - '#FFC3FF'
    - '#FF49FF'
  saturation: 0.7502685
  brandStrength: 0.1188769
  rhythmicContrast: 0.6654136
content_rating:
  adult: false
typography_spectrum: 0.2598566
opengraph: {}
title: GUITAR STARZ
