collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6660693
  brandStrength: 0.1188769
  lightness: 0.7222221
  brandColors:
    - '#FFFFFF'
    - '#231F20'
    - '#7A7879'
    - '#CAC8C9'
    - '#595758'
  rhythmicContrast: 0.5919952
typography_spectrum: 0.2598566
layout_spectrum: 1
name: Guitar Starz
