collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.2598566
color:
  saturation: 0.6660693
  brandStrength: 0.1188769
  lightness: 0.7222221
  brandColors:
    - '#FFFDFF'
    - '#0D0A15'
    - '#F46F06'
    - '#FFAD71'
    - '#056F34'
  rhythmicContrast: 0.5919952
layout_spectrum: 1
name: Guitar Starz
