collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
typography_spectrum: 0.2598566
color:
  saturation: 0.6660693
  brandStrength: 0.1188769
  lightness: 0.7222221
  brandColors:
    - '#000000'
    - '#303133'
    - '#666769'
    - '#EAEBED'
    - '#C69758'
  rhythmicContrast: 0.5919952
layout_spectrum: 1
name: Guitar Starz
